/**
 * Contract test: EvalServer OpenAPI schema vs. the Node-side request shapes.
 *
 * Loads the committed EvalServer/openapi.json artifact (generated by
 * EvalServer/scripts/export_openapi.py) and asserts that the request-body
 * schema of every endpoint the Node proxy/Clients rely on matches
 * EVAL_SERVER_REQUEST_SHAPES — both required fields and property names.
 * Any drift on either side fails this test.
 *
 * Follows the Node↔Python parity pattern of deepEvalRoutes.test.ts.
 */

import * as fs from "fs";
import * as path from "path";
import { EVAL_SERVER_REQUEST_SHAPES } from "../../types/evalServer.types";

const OPENAPI_PATH = path.resolve(__dirname, "../../../EvalServer/openapi.json");

interface OpenApiSpec {
  paths?: Record<string, Record<string, unknown>>;
  components?: { schemas?: Record<string, { required?: string[]; properties?: object }> };
}

const spec: OpenApiSpec = JSON.parse(fs.readFileSync(OPENAPI_PATH, "utf8"));

describe("EvalServer OpenAPI contract", () => {
  it("openapi.json artifact exists and parses", () => {
    expect(spec.paths).toBeDefined();
    expect(spec.components?.schemas).toBeDefined();
  });

  for (const [operationId, expected] of Object.entries(EVAL_SERVER_REQUEST_SHAPES)) {
    const [method, urlPath] = operationId.split(" ");

    it(`${operationId} request body matches the Node client shape`, () => {
      const operation = spec.paths?.[urlPath]?.[method.toLowerCase()] as
        | { requestBody?: { content?: { "application/json"?: { schema?: { $ref?: string } } } } }
        | undefined;
      expect(operation).toBeDefined();

      const ref = operation?.requestBody?.content?.["application/json"]?.schema?.$ref;
      expect(ref).toBeDefined();

      const schemaName = ref!.split("/").pop()!;
      const schema = spec.components!.schemas![schemaName];
      expect(schema).toBeDefined();

      expect([...(schema.required ?? [])].sort()).toEqual([...expected.required].sort());
      expect(Object.keys(schema.properties ?? {}).sort()).toEqual([...expected.properties].sort());
    });
  }
});
