import type { Page } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";

/**
 * A rule that axe is told not to run, together with the reason it is deferred
 * and what would close it out. A bare rule id is not a suppression — it is an
 * omission; every entry here has to say why it exists.
 */
export interface DeferredRule {
  /** Why this rule cannot simply be fixed today. */
  reason: string;
  /** What has to happen for the suppression to be removed. */
  resolvedBy: string;
}

/**
 * Rules suppressed for every scanned page.
 *
 * Two things may live here, and nothing else:
 *
 *   1. Design- or token-level rules, where the fix is a palette decision rather
 *      than a code change.
 *   2. Rules whose violations originate inside third-party markup that the app
 *      does not author and cannot reach.
 *
 * Component-level defects — an icon button with no accessible name, an input
 * with no label, a combobox with no name — are NOT deferrable. They are single
 * -component fixes, and suppressing them is precisely what makes a green
 * accessibility suite meaningless. Anything that applies to one page only gets
 * a per-test suppression via `alsoDisable` instead, so it stays visible where
 * it applies.
 */
export const DEFERRED_AXE_RULES: Record<string, DeferredRule> = {
  "color-contrast": {
    reason:
      "The green primary (#13715B) and the muted greys used for secondary text " +
      "and disabled controls fall below 4.5:1 in several combinations. Fixing " +
      "this is a palette decision, not a markup change, and it affects every " +
      "screen rather than any one component.",
    resolvedBy:
      "A design-token review that sets accessible foreground/background pairs " +
      "for the shared palette in Clients/src/presentation/themes.",
  },
  "aria-valid-attr-value": {
    reason:
      "MUI Tabs render each tab with aria-controls pointing at its panel id, " +
      "but the panel is only mounted once the tab is selected, so axe sees a " +
      "dangling reference on every tabbed page. The ids are generated by MUI " +
      "internals and are not reachable from application code or props.",
    resolvedBy:
      "An upstream MUI fix, or replacing MUI Tabs with a house tab component " +
      "that keeps all panels mounted.",
  },
};

const WCAG_TAGS = ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"] as const;

/** How long the DOM must stop mutating before a page counts as settled. */
const DOM_QUIET_MS = 500;
/** Upper bound on settling, for pages that never fully stop animating. */
const DOM_SETTLE_TIMEOUT_MS = 15_000;

/**
 * Waits until the DOM has stopped changing.
 *
 * Scanning too early is the failure mode this guards against: a page whose
 * chrome has rendered but whose table rows have not will report zero
 * violations no matter how honest the rule configuration is. Waiting on a
 * single locator is not enough, because the locator that proves "the page
 * loaded" is usually part of the chrome.
 */
async function waitForDomToSettle(page: Page) {
  await page.waitForLoadState("domcontentloaded");

  await page.evaluate(
    ({ quietMs, timeoutMs }) =>
      new Promise<void>((resolve) => {
        let quietTimer: number | undefined;

        const finish = () => {
          observer.disconnect();
          window.clearTimeout(quietTimer);
          window.clearTimeout(deadline);
          resolve();
        };

        const restartQuietTimer = () => {
          window.clearTimeout(quietTimer);
          quietTimer = window.setTimeout(finish, quietMs);
        };

        const observer = new MutationObserver(restartQuietTimer);
        const deadline = window.setTimeout(finish, timeoutMs);

        observer.observe(document.body, {
          childList: true,
          subtree: true,
          attributes: true,
          characterData: true,
        });
        restartQuietTimer();
      }),
    { quietMs: DOM_QUIET_MS, timeoutMs: DOM_SETTLE_TIMEOUT_MS },
  );
}

export interface AnalyzeOptions {
  /**
   * Extra rules to disable for this page only, each with its justification.
   * Use this rather than adding to DEFERRED_AXE_RULES when the reason is
   * specific to one screen — the suppression then stays where a reader of that
   * spec will see it.
   */
  alsoDisable?: Record<string, DeferredRule>;
}

/**
 * Runs axe over the WCAG 2.0/2.1 A and AA rule sets and returns the critical
 * and serious violations. The page is allowed to settle first, so the scan
 * sees the DOM a user would.
 */
export async function analyzeCriticalAndSeriousViolations(
  page: Page,
  options: AnalyzeOptions = {},
) {
  await waitForDomToSettle(page);

  const disabled = { ...DEFERRED_AXE_RULES, ...options.alsoDisable };

  const results = await new AxeBuilder({ page })
    .withTags([...WCAG_TAGS])
    .disableRules(Object.keys(disabled))
    .analyze();

  return results.violations.filter(
    (violation) => violation.impact === "critical" || violation.impact === "serious",
  );
}

type Violation = Awaited<ReturnType<typeof analyzeCriticalAndSeriousViolations>>[number];

/**
 * Collapses violations into one readable line each.
 *
 * Asserting on the raw axe objects prints roughly a thousand lines of nested
 * detail per failure, which is unreadable in a CI log. The line carries the
 * rule, the impact, how many nodes failed and the first offending selector —
 * enough to find the defect. Full detail belongs in the report artifact.
 */
export function summarizeViolations(violations: Violation[]): string[] {
  return violations.map((violation) => {
    const firstTarget = violation.nodes[0]?.target?.join(" ") ?? "(no target)";
    return `${violation.id} (${violation.impact}, ${violation.nodes.length} node(s)) — ${firstTarget}`;
  });
}
