/**
 * STATIC ROADMAP MANIFEST — generated, do not hand-edit individual rows.
 *
 * Derived from the AI tool catalogue in <repo-root>/tool_list_.md, which is
 * the complete tool inventory referenced by "AI Implementation Plan.md"
 * (263 tools claimed; the catalogue actually enumerates 265 rows —
 * the discrepancy is surfaced via the `sources` block of the roadmap API
 * response rather than silently resolved).
 *
 * - phase 0: the 47 pre-plan "Existing" read-only tools (baseline)
 * - phase 1: the new tools whose delivery is the plan's Phase 1 objective
 * - kind: "write" iff the name carries the catalogue's `agent_` prefix
 *
 * Regenerate with: node Servers/scripts/generateAdvisorRoadmapManifest.mjs
 */

import type { RoadmapManifestEntry } from "./types";

export const ROADMAP_MANIFEST: RoadmapManifestEntry[] = [
  {
    id: 1,
    name: "fetch_risks",
    description: "",
    domain: "Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 2,
    name: "get_risk_analytics",
    description: "",
    domain: "Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 3,
    name: "get_executive_summary",
    description: "",
    domain: "Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 4,
    name: "get_risk_history_timeseries",
    description: "",
    domain: "Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 5,
    name: "fetch_model_inventories",
    description: "",
    domain: "Model Inventory",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 6,
    name: "get_model_inventory_analytics",
    description: "",
    domain: "Model Inventory",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 7,
    name: "get_model_inventory_executive_summary",
    description: "",
    domain: "Model Inventory",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 8,
    name: "fetch_model_risks",
    description: "",
    domain: "Model Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 9,
    name: "get_model_risk_analytics",
    description: "",
    domain: "Model Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 10,
    name: "get_model_risk_executive_summary",
    description: "",
    domain: "Model Risk",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 11,
    name: "fetch_vendors",
    description: "",
    domain: "Vendor",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 12,
    name: "fetch_vendor_risks",
    description: "",
    domain: "Vendor",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 13,
    name: "get_vendor_analytics",
    description: "",
    domain: "Vendor",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 14,
    name: "get_vendor_executive_summary",
    description: "",
    domain: "Vendor",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 15,
    name: "fetch_incidents",
    description: "",
    domain: "Incident",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 16,
    name: "get_incident_analytics",
    description: "",
    domain: "Incident",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 17,
    name: "get_incident_executive_summary",
    description: "",
    domain: "Incident",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 18,
    name: "fetch_tasks",
    description: "",
    domain: "Task",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 19,
    name: "get_task_analytics",
    description: "",
    domain: "Task",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 20,
    name: "get_task_executive_summary",
    description: "",
    domain: "Task",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 21,
    name: "fetch_policies",
    description: "",
    domain: "Policy",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 22,
    name: "get_policy_analytics",
    description: "",
    domain: "Policy",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 23,
    name: "get_policy_executive_summary",
    description: "",
    domain: "Policy",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 24,
    name: "search_policy_templates",
    description: "",
    domain: "Policy",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 25,
    name: "get_template_recommendations",
    description: "",
    domain: "Policy",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 26,
    name: "fetch_use_cases",
    description: "",
    domain: "Use Case",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 27,
    name: "get_use_case_analytics",
    description: "",
    domain: "Use Case",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 28,
    name: "get_use_case_executive_summary",
    description: "",
    domain: "Use Case",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 29,
    name: "fetch_datasets",
    description: "",
    domain: "Dataset",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 30,
    name: "get_dataset_analytics",
    description: "",
    domain: "Dataset",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 31,
    name: "get_dataset_executive_summary",
    description: "",
    domain: "Dataset",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 32,
    name: "fetch_frameworks",
    description: "",
    domain: "Framework",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 33,
    name: "get_framework_analytics",
    description: "",
    domain: "Framework",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 34,
    name: "fetch_training_records",
    description: "",
    domain: "Training",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 35,
    name: "get_training_analytics",
    description: "",
    domain: "Training",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 36,
    name: "get_training_executive_summary",
    description: "",
    domain: "Training",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 37,
    name: "fetch_evidence",
    description: "",
    domain: "Evidence",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 38,
    name: "get_evidence_analytics",
    description: "",
    domain: "Evidence",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 39,
    name: "get_evidence_executive_summary",
    description: "",
    domain: "Evidence",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 40,
    name: "fetch_reports",
    description: "",
    domain: "Reporting",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 41,
    name: "get_reporting_analytics",
    description: "",
    domain: "Reporting",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 42,
    name: "fetch_trust_center_overview",
    description: "",
    domain: "AI Trust Centre",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 43,
    name: "get_trust_center_analytics",
    description: "",
    domain: "AI Trust Centre",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 44,
    name: "fetch_agent_primitives",
    description: "",
    domain: "Agent Discovery",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 45,
    name: "get_agent_discovery_analytics",
    description: "",
    domain: "Agent Discovery",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 46,
    name: "get_agent_discovery_executive_summary",
    description: "",
    domain: "Agent Discovery",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 47,
    name: "generate_chart",
    description: "",
    domain: "Native (Visualization)",
    category: "existing",
    phase: 0,
    kind: "read",
  },
  {
    id: 48,
    name: "agent_create_risk",
    description: "Create new risk",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 49,
    name: "agent_update_risk",
    description: "Update risk (severity, likelihood, etc.)",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 50,
    name: "agent_delete_risk",
    description: "Delete risk (soft delete)",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 51,
    name: "agent_assign_risk_owner",
    description: "Assign owner to risk",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 52,
    name: "agent_change_risk_status",
    description: "Change mitigation status",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 53,
    name: "agent_bulk_update_risk_status",
    description: "Bulk update risk status",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 54,
    name: "agent_link_risk_to_project",
    description: "Link risk to project",
    domain: "Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 55,
    name: "agent_register_model",
    description: "Register new model",
    domain: "Model Inventory",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 56,
    name: "agent_update_model",
    description: "Update model information",
    domain: "Model Inventory",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 57,
    name: "agent_update_model_lifecycle_phase",
    description: "Change lifecycle phase (dev→staging→prod)",
    domain: "Model Inventory",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 58,
    name: "agent_retire_model",
    description: "Retire model",
    domain: "Model Inventory",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 59,
    name: "agent_delete_model",
    description: "Delete model",
    domain: "Model Inventory",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 60,
    name: "agent_link_model_to_project",
    description: "Link model to project",
    domain: "Model Inventory",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 61,
    name: "agent_create_model_risk",
    description: "Create model risk",
    domain: "Model Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 62,
    name: "agent_update_model_risk",
    description: "Update model risk",
    domain: "Model Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 63,
    name: "agent_change_model_risk_status",
    description: "Change risk status",
    domain: "Model Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 64,
    name: "agent_delete_model_risk",
    description: "Delete model risk",
    domain: "Model Risk",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 65,
    name: "agent_create_vendor",
    description: "Register new vendor",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 66,
    name: "agent_update_vendor",
    description: "Update vendor information",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 67,
    name: "agent_delete_vendor",
    description: "Delete vendor",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 68,
    name: "agent_create_vendor_risk",
    description: "Create vendor risk",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 69,
    name: "agent_update_vendor_risk",
    description: "Update vendor risk",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 70,
    name: "agent_delete_vendor_risk",
    description: "Delete vendor risk",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 71,
    name: "agent_flag_vendor_for_review",
    description: "Flag vendor for review",
    domain: "Vendor",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 72,
    name: "agent_create_incident",
    description: "Create new incident",
    domain: "Incident",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 73,
    name: "agent_update_incident",
    description: "Update incident",
    domain: "Incident",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 74,
    name: "agent_update_incident_status",
    description: "Change incident status",
    domain: "Incident",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 75,
    name: "agent_archive_incident",
    description: "Archive incident",
    domain: "Incident",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 76,
    name: "agent_delete_incident",
    description: "Delete incident",
    domain: "Incident",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 77,
    name: "agent_create_task",
    description: "Create new task",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 78,
    name: "agent_update_task",
    description: "Update task",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 79,
    name: "agent_assign_task",
    description: "Assign task to user",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 80,
    name: "agent_update_task_status",
    description: "Change task status",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 81,
    name: "agent_set_task_priority",
    description: "Set task priority",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 82,
    name: "agent_delete_task",
    description: "Delete task",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 83,
    name: "agent_restore_task",
    description: "Restore deleted task",
    domain: "Task",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 84,
    name: "agent_create_policy",
    description: "Create new policy",
    domain: "Policy",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 85,
    name: "agent_update_policy",
    description: "Update policy content",
    domain: "Policy",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 86,
    name: "agent_submit_policy_for_review",
    description: "Submit policy for review",
    domain: "Policy",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 87,
    name: "agent_approve_policy_review",
    description: "Approve policy review",
    domain: "Policy",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 88,
    name: "agent_delete_policy",
    description: "Delete policy",
    domain: "Policy",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 89,
    name: "agent_create_use_case",
    description: "Create new use case",
    domain: "Use Case / Project",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 90,
    name: "agent_update_use_case",
    description: "Update use case",
    domain: "Use Case / Project",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 91,
    name: "agent_update_use_case_status",
    description: "Change status",
    domain: "Use Case / Project",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 92,
    name: "agent_add_member_to_use_case",
    description: "Add member",
    domain: "Use Case / Project",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 93,
    name: "agent_delete_use_case",
    description: "Delete use case",
    domain: "Use Case / Project",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 94,
    name: "agent_register_dataset",
    description: "Register new dataset",
    domain: "Dataset",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 95,
    name: "agent_update_dataset",
    description: "Update dataset",
    domain: "Dataset",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 96,
    name: "agent_link_dataset_to_model",
    description: "Link dataset to model",
    domain: "Dataset",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 97,
    name: "agent_delete_dataset",
    description: "Delete dataset",
    domain: "Dataset",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 98,
    name: "agent_create_training_record",
    description: "Create new training record",
    domain: "Training",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 99,
    name: "agent_update_training_record",
    description: "Update training record",
    domain: "Training",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 100,
    name: "agent_assign_training_to_user",
    description: "Assign training to user",
    domain: "Training",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 101,
    name: "agent_delete_training_record",
    description: "Delete training record",
    domain: "Training",
    category: "A",
    phase: 1,
    kind: "write",
  },
  {
    id: 102,
    name: "get_risk_change_history",
    description: "Risk change history",
    domain: "Change History",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 103,
    name: "get_vendor_change_history",
    description: "Vendor change history",
    domain: "Change History",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 104,
    name: "get_model_change_history",
    description: "Model change history",
    domain: "Change History",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 105,
    name: "get_policy_change_history",
    description: "Policy change history",
    domain: "Change History",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 106,
    name: "get_incident_change_history",
    description: "Incident change history",
    domain: "Change History",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 107,
    name: "get_task_change_history",
    description: "Task change history",
    domain: "Change History",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 108,
    name: "fetch_approval_workflows",
    description: "List all workflow templates",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 109,
    name: "get_approval_workflow_detail",
    description: "Workflow detail (steps, approvers)",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 110,
    name: "fetch_pending_approvals",
    description: "List pending approvals",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 111,
    name: "fetch_my_approval_requests",
    description: "User's own requests",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 112,
    name: "get_approval_request_detail",
    description: "Request detail (timeline, status)",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 113,
    name: "get_approval_status_for_entity",
    description: "Entity approval status",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 114,
    name: "get_approval_analytics",
    description: "Approval statistics (avg. time, rejection rate)",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 115,
    name: "get_approval_executive_summary",
    description: "Approval process summary report",
    domain: "Approval Workflow",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 116,
    name: "fetch_automations",
    description: "List all automations",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 117,
    name: "get_automation_detail",
    description: "Automation detail (trigger, actions)",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 118,
    name: "fetch_automation_triggers",
    description: "List available triggers",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 119,
    name: "get_automation_history",
    description: "Execution log history",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 120,
    name: "get_automation_stats",
    description: "Success / error rates",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 121,
    name: "get_automation_analytics",
    description: "General automation analytics",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 122,
    name: "get_automation_executive_summary",
    description: "Automation summary report",
    domain: "Automation",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 123,
    name: "get_pmm_config",
    description: "Project PMM configuration",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 124,
    name: "get_pmm_active_cycle",
    description: "Active monitoring cycle",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 125,
    name: "get_pmm_cycle_detail",
    description: "Cycle details",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 126,
    name: "get_pmm_cycle_responses",
    description: "Stakeholder responses",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 127,
    name: "get_pmm_questions",
    description: "PMM questions",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 128,
    name: "fetch_pmm_reports",
    description: "PMM reports",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 129,
    name: "get_pmm_analytics",
    description: "PMM analytics (completion rate, flagged concerns)",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 130,
    name: "get_pmm_executive_summary",
    description: "PMM summary report",
    domain: "Post-Market Monitoring (PMM)",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 131,
    name: "fetch_files",
    description: "List files (project / org level)",
    domain: "File Management",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 132,
    name: "get_file_detail",
    description: "File detail (metadata, links)",
    domain: "File Management",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 133,
    name: "get_files_by_entity",
    description: "Files linked to entity",
    domain: "File Management",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 134,
    name: "get_file_change_history",
    description: "File change history",
    domain: "File Management",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 135,
    name: "get_file_analytics",
    description: "File statistics (type distribution, size)",
    domain: "File Management",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 136,
    name: "get_file_executive_summary",
    description: "File management summary",
    domain: "File Management",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 137,
    name: "fetch_virtual_folders",
    description: "List folder structure",
    domain: "Virtual Folder",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 138,
    name: "get_folder_tree",
    description: "Hierarchical folder tree",
    domain: "Virtual Folder",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 139,
    name: "get_folder_files",
    description: "Files in folder",
    domain: "Virtual Folder",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 140,
    name: "get_uncategorized_files",
    description: "Uncategorized files",
    domain: "Virtual Folder",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 141,
    name: "get_shadow_ai_summary",
    description: "General shadow AI overview",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 142,
    name: "get_shadow_ai_tools_by_events",
    description: "Tool usage by event",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 143,
    name: "get_shadow_ai_tools_by_users",
    description: "Tool usage by user",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 144,
    name: "get_shadow_ai_trend",
    description: "Time-based trend analysis",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 145,
    name: "get_shadow_ai_users_by_department",
    description: "Distribution by department",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 146,
    name: "get_shadow_ai_user_activity",
    description: "Individual user activity",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 147,
    name: "get_shadow_ai_tool_detail",
    description: "Specific tool detail",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 148,
    name: "get_shadow_ai_alert_history",
    description: "Alert history",
    domain: "Shadow AI",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 149,
    name: "fetch_ai_detection_scans",
    description: "List scan history",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 150,
    name: "get_ai_detection_scan_detail",
    description: "Scan detail (status, findings)",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 151,
    name: "get_ai_detection_findings",
    description: "AI detection findings",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 152,
    name: "get_ai_detection_security_findings",
    description: "Security findings",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 153,
    name: "get_ai_detection_security_summary",
    description: "Security summary",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 154,
    name: "get_ai_detection_governance_summary",
    description: "Governance summary",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 155,
    name: "get_ai_detection_stats",
    description: "General statistics",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 156,
    name: "get_ai_detection_compliance_mapping",
    description: "EU AI Act mapping",
    domain: "AI Detection",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 157,
    name: "fetch_entity_annotations",
    description: "All entity annotations",
    domain: "Entity Graph",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 158,
    name: "get_entity_annotation",
    description: "Single entity annotation",
    domain: "Entity Graph",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 159,
    name: "fetch_entity_graph_views",
    description: "Saved graph views",
    domain: "Entity Graph",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 160,
    name: "get_gap_rules",
    description: "Gap analysis rules",
    domain: "Entity Graph",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 161,
    name: "get_default_gap_rules",
    description: "Default gap rules",
    domain: "Entity Graph",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 162,
    name: "fetch_notes",
    description: "List notes (filtered)",
    domain: "Notes",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 163,
    name: "get_notes_for_entity",
    description: "Notes belonging to entity",
    domain: "Notes",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 164,
    name: "get_note_detail",
    description: "Note detail",
    domain: "Notes",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 165,
    name: "get_notes_analytics",
    description: "Note statistics",
    domain: "Notes",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 166,
    name: "fetch_notifications",
    description: "List notifications",
    domain: "Notification",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 167,
    name: "get_unread_notification_count",
    description: "Unread notification count",
    domain: "Notification",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 168,
    name: "get_notification_summary",
    description: "Notification summary",
    domain: "Notification",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 169,
    name: "get_notification_analytics",
    description: "Notification statistics",
    domain: "Notification",
    category: "B",
    phase: 1,
    kind: "read",
  },
  {
    id: 170,
    name: "agent_create_approval_request",
    description: "Create approval request",
    domain: "Approval Workflow",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 171,
    name: "agent_approve_approval_step",
    description: "Approve step",
    domain: "Approval Workflow",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 172,
    name: "agent_reject_approval_step",
    description: "Reject step",
    domain: "Approval Workflow",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 173,
    name: "agent_withdraw_approval_request",
    description: "Withdraw request",
    domain: "Approval Workflow",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 174,
    name: "agent_create_approval_workflow",
    description: "Create workflow template",
    domain: "Approval Workflow",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 175,
    name: "agent_create_automation",
    description: "Create new automation rule",
    domain: "Automation",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 176,
    name: "agent_update_automation",
    description: "Update automation",
    domain: "Automation",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 177,
    name: "agent_toggle_automation",
    description: "Toggle automation on/off",
    domain: "Automation",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 178,
    name: "agent_delete_automation",
    description: "Delete automation",
    domain: "Automation",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 179,
    name: "agent_create_pmm_config",
    description: "Create PMM configuration",
    domain: "Post-Market Monitoring (PMM)",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 180,
    name: "agent_update_pmm_config",
    description: "Update PMM configuration",
    domain: "Post-Market Monitoring (PMM)",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 181,
    name: "agent_add_pmm_question",
    description: "Add PMM question",
    domain: "Post-Market Monitoring (PMM)",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 182,
    name: "agent_start_pmm_cycle",
    description: "Start new monitoring cycle",
    domain: "Post-Market Monitoring (PMM)",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 183,
    name: "agent_submit_pmm_responses",
    description: "Submit stakeholder responses",
    domain: "Post-Market Monitoring (PMM)",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 184,
    name: "agent_flag_pmm_concern",
    description: "Report a concern",
    domain: "Post-Market Monitoring (PMM)",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 185,
    name: "agent_attach_file_to_entity",
    description: "Attach file to entity",
    domain: "File Management",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 186,
    name: "agent_detach_file_from_entity",
    description: "Remove file attachment",
    domain: "File Management",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 187,
    name: "agent_create_virtual_folder",
    description: "Create virtual folder",
    domain: "File Management",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 188,
    name: "agent_assign_file_to_folder",
    description: "Assign file to folder",
    domain: "File Management",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 189,
    name: "agent_remove_file_from_folder",
    description: "Remove file from folder",
    domain: "File Management",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 190,
    name: "agent_update_shadow_ai_tool_status",
    description: "Update tool governance status",
    domain: "Shadow AI",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 191,
    name: "agent_start_shadow_ai_governance",
    description: "Start governance process",
    domain: "Shadow AI",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 192,
    name: "agent_create_shadow_ai_alert_rule",
    description: "Create alert rule",
    domain: "Shadow AI",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 193,
    name: "agent_start_ai_detection_scan",
    description: "Start repository scan",
    domain: "AI Detection",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 194,
    name: "agent_cancel_ai_detection_scan",
    description: "Cancel scan",
    domain: "AI Detection",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 195,
    name: "agent_update_finding_governance",
    description: "Update finding governance status",
    domain: "AI Detection",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 196,
    name: "agent_create_entity_annotation",
    description: "Add entity annotation",
    domain: "Entity Graph",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 197,
    name: "agent_delete_entity_annotation",
    description: "Delete annotation",
    domain: "Entity Graph",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 198,
    name: "agent_save_entity_graph_view",
    description: "Save graph view",
    domain: "Entity Graph",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 199,
    name: "agent_save_gap_rules",
    description: "Save gap rules",
    domain: "Entity Graph",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 200,
    name: "agent_create_note",
    description: "Create note",
    domain: "Notes",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 201,
    name: "agent_update_note",
    description: "Update note",
    domain: "Notes",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 202,
    name: "agent_delete_note",
    description: "Delete note",
    domain: "Notes",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 203,
    name: "agent_mark_notification_read",
    description: "Mark notification as read",
    domain: "Notification",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 204,
    name: "agent_mark_all_notifications_read",
    description: "Mark all as read",
    domain: "Notification",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 205,
    name: "agent_create_evidence",
    description: "Create evidence",
    domain: "Evidence",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 206,
    name: "agent_update_evidence",
    description: "Update evidence",
    domain: "Evidence",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 207,
    name: "agent_delete_evidence",
    description: "Delete evidence",
    domain: "Evidence",
    category: "C",
    phase: 1,
    kind: "write",
  },
  {
    id: 208,
    name: "get_eu_ai_act_control_categories",
    description: "Get control categories",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 209,
    name: "get_eu_ai_act_controls_by_category",
    description: "Controls by category",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 210,
    name: "get_eu_ai_act_project_compliance",
    description: "Project compliance status",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 211,
    name: "get_eu_ai_act_project_assessment",
    description: "Project assessment status",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 212,
    name: "get_eu_ai_act_compliance_progress",
    description: "Compliance progress percentage",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 213,
    name: "agent_save_eu_ai_act_control",
    description: "Save / update control",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 214,
    name: "agent_save_eu_ai_act_assessment_answer",
    description: "Save assessment answer",
    domain: "EU AI Act",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 215,
    name: "get_iso42001_clauses_structure",
    description: "Clause structure",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 216,
    name: "get_iso42001_annexes_structure",
    description: "Annex structure",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 217,
    name: "get_iso42001_project_clauses",
    description: "Project clause status",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 218,
    name: "get_iso42001_project_annexes",
    description: "Project annex status",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 219,
    name: "get_iso42001_progress",
    description: "Progress percentage",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 220,
    name: "agent_save_iso42001_clauses",
    description: "Save clauses",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 221,
    name: "agent_save_iso42001_annexes",
    description: "Save annexes",
    domain: "ISO 42001",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 222,
    name: "get_iso27001_clauses_structure",
    description: "Clause structure",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 223,
    name: "get_iso27001_annexes_structure",
    description: "Annex structure",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 224,
    name: "get_iso27001_project_clauses",
    description: "Project clause status",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 225,
    name: "get_iso27001_project_annexes",
    description: "Project annex status",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 226,
    name: "get_iso27001_progress",
    description: "Progress percentage",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 227,
    name: "agent_save_iso27001_clauses",
    description: "Save clauses",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 228,
    name: "agent_save_iso27001_annexes",
    description: "Save annexes",
    domain: "ISO 27001",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 229,
    name: "get_nist_functions",
    description: "List NIST functions",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 230,
    name: "get_nist_categories_by_function",
    description: "Categories by function",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 231,
    name: "get_nist_subcategory_detail",
    description: "Subcategory detail",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 232,
    name: "get_nist_progress",
    description: "Overall progress",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 233,
    name: "get_nist_progress_by_function",
    description: "Progress by function",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 234,
    name: "get_nist_status_breakdown",
    description: "Status breakdown",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "read",
  },
  {
    id: 235,
    name: "agent_update_nist_subcategory",
    description: "Update subcategory",
    domain: "NIST AI RMF",
    category: "D",
    phase: 1,
    kind: "write",
  },
  {
    id: 236,
    name: "get_compliance_score",
    description: "Overall compliance score",
    domain: "Compliance & Dashboard",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 237,
    name: "get_compliance_details",
    description: "Detailed compliance analysis",
    domain: "Compliance & Dashboard",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 238,
    name: "get_dashboard_overview",
    description: "Dashboard summary data",
    domain: "Compliance & Dashboard",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 239,
    name: "get_project_compliance_progress",
    description: "Project-level compliance",
    domain: "Compliance & Dashboard",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 240,
    name: "get_all_projects_compliance",
    description: "All projects compliance",
    domain: "Compliance & Dashboard",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 241,
    name: "get_project_stats",
    description: "Project statistics",
    domain: "Compliance & Dashboard",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 242,
    name: "global_search",
    description: "Search across all entities",
    domain: "Global Search",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 243,
    name: "search_within_entity",
    description: "Search within a specific entity type",
    domain: "Global Search",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 244,
    name: "agent_create_share_link",
    description: "Create share link",
    domain: "Share Link",
    category: "E",
    phase: 1,
    kind: "write",
  },
  {
    id: 245,
    name: "fetch_share_links",
    description: "List share links",
    domain: "Share Link",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 246,
    name: "agent_revoke_share_link",
    description: "Revoke share link",
    domain: "Share Link",
    category: "E",
    phase: 1,
    kind: "write",
  },
  {
    id: 247,
    name: "get_ce_marking_status",
    description: "CE marking status",
    domain: "CE Marking",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 248,
    name: "agent_update_ce_marking",
    description: "Update CE marking",
    domain: "CE Marking",
    category: "E",
    phase: 1,
    kind: "write",
  },
  {
    id: 249,
    name: "get_policy_linked_objects",
    description: "Objects linked to policy",
    domain: "Policy Linked Objects",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 250,
    name: "agent_link_object_to_policy",
    description: "Link object to policy",
    domain: "Policy Linked Objects",
    category: "E",
    phase: 1,
    kind: "write",
  },
  {
    id: 251,
    name: "agent_unlink_object_from_policy",
    description: "Remove link",
    domain: "Policy Linked Objects",
    category: "E",
    phase: 1,
    kind: "write",
  },
  {
    id: 252,
    name: "fetch_event_logs",
    description: "List event logs",
    domain: "Event Log / Audit",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 253,
    name: "get_audit_trail_for_entity",
    description: "Entity audit trail",
    domain: "Event Log / Audit",
    category: "E",
    phase: 1,
    kind: "read",
  },
  {
    id: 254,
    name: "fetch_users",
    description: "List users",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 255,
    name: "get_user_detail",
    description: "User detail",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 256,
    name: "get_user_progress",
    description: "User progress",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 257,
    name: "fetch_roles",
    description: "List roles",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 258,
    name: "get_organization_detail",
    description: "Organization information",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 259,
    name: "fetch_invitations",
    description: "List invitations",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 260,
    name: "agent_send_invitation",
    description: "Send invitation",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "write",
  },
  {
    id: 261,
    name: "get_subscription_info",
    description: "Subscription information",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 262,
    name: "fetch_auto_drivers",
    description: "List auto drivers",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 263,
    name: "agent_run_auto_driver",
    description: "Run auto driver",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "write",
  },
  {
    id: 264,
    name: "fetch_slack_webhooks",
    description: "List Slack webhooks",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "read",
  },
  {
    id: 265,
    name: "agent_send_slack_test_message",
    description: "Send Slack test message",
    domain: "Admin / Configuration",
    category: "F",
    phase: 1,
    kind: "write",
  },
];
