export type UserLanguage = "en" | "de" | "fr" | "es";

export interface IUserPreferences {
  id?: number; // auto generated by DB
  user_id: number;
  date_format: "DD-MM-YYYY" | "MM-DD-YYYY" | "DD/MM/YY" | "MM/DD/YY";
  language?: UserLanguage;
  /** When true, the Advisor runs independent sub-tasks in parallel. */
  parallel_agents?: boolean;
}
