export interface IVendor {
  id?: number; // auto generated by database
  order_no?: number; // gets assigned from the structure (keeping for compatibility)
  projects?: any[]; // required by validation, but optional in interface for compatibility
  vendor_name: string; // won't get any values, will be filled by user
  vendor_provides: string; // won't get any values, will be filled by user
  assignee: number; // won't get any values, will be filled by user
  website: string; // won't get any values, will be filled by user
  vendor_contact_person: string; // won't get any values, will be filled by user
  review_result?: string; // optional field, can be filled by user
  review_status?: "Not started" | "In review" | "Reviewed" | "Requires follow-up"; // optional field, can be filled by user
  reviewer?: number | null; // optional field, can be filled by user
  review_date?: Date; // optional field, can be filled by user
  created_at?: Date;
  updated_at?: Date;
  // Vendor scorecard fields - optional, will be filled by user
  data_sensitivity?:
    | "None"
    | "Internal only"
    | "Personally identifiable information (PII)"
    | "Financial data"
    | "Health data (e.g. HIPAA)"
    | "Model weights or AI assets"
    | "Other sensitive data";
  business_criticality?:
    | "Low (vendor supports non-core functions)"
    | "Medium (affects operations but is replaceable)"
    | "High (critical to core services or products)";
  past_issues?:
    | "None"
    | "Minor incident (e.g. small delay, minor bug)"
    | "Major incident (e.g. data breach, legal issue)";
  regulatory_exposure?:
    | "None"
    | "GDPR (EU)"
    | "HIPAA (US)"
    | "SOC 2"
    | "ISO 27001"
    | "EU AI act"
    | "CCPA (california)"
    | "Other";
  risk_score?: number;
  // DORA Register of Information fields (descriptive)
  is_ict_provider?: boolean;
  ict_service_type?:
    | "Cloud services"
    | "Data analysis"
    | "Security services"
    | "Network infrastructure"
    | "Software or applications"
    | "IT project management"
    | "Other ICT services";
  function_criticality?: "Critical" | "Important" | "Not critical";
  substitutability?: "Easily substitutable" | "Difficult to substitute" | "Not substitutable";
  has_exit_plan?: boolean;
  country_of_provision?: string;
  provider_lei?: string;
  custom_fields?: Array<{
    definition_id: number;
    field_key: string;
    label: string;
    field_type: string;
    value: unknown;
  }>;
}
